#!/usr/bin/env python3


################ Lispy: Scheme Interpreter in Python

## (c) Peter Norvig, 2010; See http://norvig.com/lispy.html

import argparse
import io
import re
import os
import sys

class Program(object):
    def __init__(self, debug_level):
        self.total_if_count = 0
        self.total_lambda_count = 0
        self.debug_level = debug_level

        self.regions = []
        self.main_region = None

    def new_region(self):
        index = len(self.regions)
        region = io.StringIO("")
        self.regions.append(region)
        return index

    def register_main(self, region):
        """
        Register a region as the main region.
        This region will be emitted before all others.
        """
        self.main_region = region

    def output(self, region, s):
        print(s, file=self.regions[region])

    def debug_comment(self, out, level, comment):
        if self.debug_level >= level:
            self.output(out, "; %s" % comment)

    def emit(self):
        if self.main_region is not None:
            print("; region %d (main)" % self.main_region)
            print(self.regions[self.main_region].getvalue())

        for i, region in enumerate(self.regions):
            if i == self.main_region:
                continue
            print("; region %d" % i)
            print(region.getvalue())

################ Instructions

class Instruction(object):
    def __init__(self, program, region, op1=None, op2=None):
        self.program = program
        self.region = region
        self.op1 = op1
        self.op2 = op2

        if op1 is None and op2 is not None:
            raise ValueError("'%s' got a second operand, but not a first" %
                                (self.name))

        if op2 is not None:
            passed_ops = 2
        elif op1 is not None:
            passed_ops = 1
        else:
            passed_ops = 0

        if passed_ops != self.ops:
            raise ValueError("'%s' expected %d ops, found %d" %
                    (self.name, self.ops, passed_ops))

    def __repr__(self):
        r = self.name

        if self.op1 is not None:
            r += " " + str(self.op1)

        if self.op2 is not None:
            r += " " + str(self.op2)

        return r

    def emit(self):
        self.program.output(self.region, str(self))

class Add(Instruction):
    name = 'ADD'
    ops = 0

class Sub(Instruction):
    name = 'SUB'
    ops = 0

class Mul(Instruction):
    name = 'MUL'
    ops = 0

class Div(Instruction):
    name = 'DIV'
    ops = 0

class Cons(Instruction):
    name = 'CONS'
    ops = 0

class Car(Instruction):
    name = 'CAR'
    ops = 0

class Cdr(Instruction):
    name = 'CDR'
    ops = 0

class Ceq(Instruction):
    name = 'CEQ'
    ops = 0

class Cgt(Instruction):
    name = 'CGT'
    ops = 0

class Cgte(Instruction):
    name = 'CGTE'
    ops = 0

class Atom(Instruction):
    name = 'ATOM'
    ops = 0

class Ldc(Instruction):
    name = 'LDC'
    ops = 1

class Ld(Instruction):
    name = 'LD'
    ops = 2

class St(Instruction):
    name = 'ST'
    ops = 2

class Ldf(Instruction):
    name = 'LDF'
    ops = 1

class Ap(Instruction):
    name = 'AP'
    ops = 1

class Rtn(Instruction):
    name = 'RTN'
    ops = 0

class Sel(Instruction):
    name = 'SEL'
    ops = 2

class Tsel(Instruction):
    name = 'TSEL'
    ops = 2

class Join(Instruction):
    name = 'JOIN'
    ops = 0

class Builtin(object):
    def __init__(self, instr):
        self.instr = instr

################ Symbol, Env classes

Symbol = str
EnvRef = int    # Index into environment

class Env(dict):
    "An environment: a dict of {'var':val} pairs, with an outer Env."
    def __init__(self, outer=None):
        self.outer = outer

    def find(self, var, depth=0):
        "Find the innermost Env where var appears."
        if var in self:
            return self, depth
        elif self.outer:
            return self.outer.find(var, depth+1)
        else:
            raise KeyError("Undefined reference to '%s'" % var)

def add_globals(env):
    env.update({
        '+':    Builtin(Add),
        '-':    Builtin(Sub),
        '*':    Builtin(Mul),
        '/':    Builtin(Div),
        '==':   Builtin(Ceq),
        '>':    Builtin(Cgt),
        '>=':   Builtin(Cgte),
        'atom': Builtin(Atom),
        'cons': Builtin(Cons),
        'car':  Builtin(Car),
        'cdr':  Builtin(Cdr),
    })
    return env

global_env = add_globals(Env())

isa = isinstance

################ Functions, Labels

class Function(object):
    def __init__(self, name, num_args):
        self.name = name
        self.num_args = num_args

class Label(object):
    def __init__(self, name, program, region):
        self.name = name
        self.program = program
        self.region = region

    def emit(self):
        self.program.output(self.region, "%s:" % self.name)

    def __repr__(self):
        return self.name

################ Expressions

class Expression(object):
    def __init__(self, expression, program, region, env=global_env):
        self.program = program
        self.expression = expression
        self.env = env
        self.region = region

        self.program.debug_comment(region, 3, "New expression: %s" % expression)

    def subexpression(self, exp, env=None, region=None):
        if env is None:
            env = self.env
        if region is None:
            region = self.region

        return Expression(exp, self.program, region, env)

    def instruction(self, instr, op1=None, op2=None, region=None):
        if region is None:
            region = self.region

        return instr(self.program, region, op1=op1, op2=op2)

    def label(self, name, region=None):
        if region is None:
            region = self.region

        return Label(name, self.program, region)

    def define_func(self, given_name, args, body):
        name = given_name
        if not given_name:
            name = "lambda_%d" % self.program.total_lambda_count
            self.program.total_lambda_count += 1

        # Allocate space to emit the function
        region = self.program.new_region()

        # main is a special case, which should be emitted
        # first
        if name == 'main':
            self.program.register_main(region)

        self.program.debug_comment(region, 1, "function %s %s" % (name, to_string(args)))
        self.label(name, region=region).emit()

        func = Function(name, len(args))

        if given_name:
            self.env[given_name] = func

        local_env = Env(outer=self.env)

        # Assign space in environment
        for i, a in enumerate(args):
            local_env[a] = EnvRef(i)

        # This gives us parent frames from the point of function definition
        body = self.subexpression(body, env=local_env, region=region)
        body.emit()

        self.instruction(Rtn, region=region).emit()
        return func

    def emit_if(self, test, conseq, alt):
        true_label = self.label("if_true_%d" % self.program.total_if_count)
        false_label = self.label("if_false_%d" % self.program.total_if_count)
        after_label = self.label("if_after_%d" % self.program.total_if_count)
        self.program.total_if_count += 1

        # Execute the test condition
        test = self.subexpression(test)
        test.emit()

        # Jump to true or false case
        self.instruction(Sel, true_label, false_label).emit()

        # After true or false case completion, jump to end
        self.instruction(Ldc, 1).emit()
        self.instruction(Tsel, after_label, 0).emit()

        # True case, then join back to above
        true_label.emit()
        conseq = self.subexpression(conseq)
        conseq.emit()
        self.instruction(Join).emit()

        # False case, then join back to above
        false_label.emit()
        alt = self.subexpression(alt)
        alt.emit()
        self.instruction(Join).emit()

        # When done, jump to next instructions
        after_label.emit()

    def emit(self):
        "Evaluate an expression in an environment."
        x = self.expression
        self.program.debug_comment(self.region, 3, "emit(%r)" % x)
        if isa(x, Symbol):             # variable reference
            env, depth = self.env.find(x)
            sym = env[x]
            self.program.debug_comment(self.region, 4, "Symbol %s = %s" % (x, sym))
            if isa(sym, EnvRef):
                self.instruction(Ld, depth, sym).emit()
                return
            return sym
        elif not isa(x, list):         # constant literal
            self.instruction(Ldc, x).emit()
            return
        elif x[0] == 'if':             # (if test conseq alt)
            (_, test, conseq, alt) = x
            self.emit_if(test, conseq, alt)
        elif x[0] == 'lambda':          # (lambda (var*) exp)
            (_, args, exp) = x
            func = self.define_func(None, args, exp)
            self.instruction(Ldf, func.name).emit()
        elif x[0] == 'defun':           # Function definition
            # (defun name (a1 a2) (body))
            assert(len(x) == 4)
            (_, name, args, body) = x
            self.define_func(name, args, body)
        elif x[0] == 'funcall':         # Function call
            (_, func, *args) = x
            self.program.debug_comment(self.region, 3, "func '%s' args '%s'" % (func, args))
            # Emit arguments
            [self.subexpression(exp).emit() for exp in args]
            # Emit function
            self.subexpression(func).emit()
            # Jump to function
            self.instruction(Ap, len(args)).emit()
        elif x[0] == 'asmcall':         # Direct call to label, no lookup
            (_, label, *args) = x
            if not isa(label, Symbol):
                raise TypeError("asmcall label must be a raw symbol")
            self.program.debug_comment(self.region, 3, "func '%s' args '%s'" % (label, args))
            # Emit arguments
            [self.subexpression(exp).emit() for exp in args]
            # Jump to function
            self.instruction(Ldf, label).emit()
            self.instruction(Ap, len(args)).emit()
        else:                          # (proc exp*)
            self.program.debug_comment(self.region, 3, "proc '%s'" % x[0])
            exps = [self.subexpression(exp).emit() for exp in x]
            proc = exps.pop(0)
            if isa(proc, Builtin):
                self.instruction(proc.instr).emit()
            elif isa(proc, Function):
                if len(exps) != proc.num_args:
                    raise ValueError("Call to '%s' expected %d arguments, but found %d" % \
                                        (proc.name, proc.num_args, len(exps)))
                self.instruction(Ldf, proc.name).emit()
                self.instruction(Ap, proc.num_args).emit()
            elif proc is not None or exps :
                # A simple expression like ((exp)) will be emitted without
                # returning a proc, which is fine, but multiple exps in
                # one exp is not valid ((exp) (exp))
                raise ValueError("Invalid proc '%s' in exp %r" % (proc, x))

################ read, and user interaction

def read(s):
    "Read a Scheme expression from a string."
    return read_from(tokenize(s))

def tokenize(s):
    "Convert a string into a list of tokens."
    return s.replace('(',' ( ').replace(')',' ) ').split()

def read_from(tokens):
    "Read an expression from a sequence of tokens."
    if len(tokens) == 0:
        raise SyntaxError('unexpected EOF while reading')
    token = tokens.pop(0)
    if '(' == token:
        L = []
        while tokens[0] != ')':
            L.append(read_from(tokens))
        tokens.pop(0) # pop off ')'
        return L
    elif ')' == token:
        raise SyntaxError('unexpected )')
    else:
        return atom(token)

def atom(token):
    "Numbers become numbers; every other token is a symbol."
    try: return int(token)
    except ValueError:
        return Symbol(token)

def to_string(exp):
    "Convert a Python object back into a Lisp-readable string."
    return '('+' '.join(map(to_string, exp))+')' if isa(exp, list) else str(exp)

def read_file(filename, directories):
    for directory in directories:
        f = os.path.join(directory, filename)
        try:
            with open(f) as source_file:
                return source_file.read(), os.path.abspath(f)
        except FileNotFoundError:
            continue

    raise FileNotFoundError("'%s' not found in %r" % (filename, directories))

include_pattern = re.compile(r"""^!include "(?P<file>.+)"\s*$""")

def preprocess(source, search_path, included=None):
    """
    Run the source through the preprocessor

    * Strips comments
    * Includes files
    """
    processed = []
    #print("preprocessing '%s'" % source)

    if not included:
        included = []

    for line in source.split('\n'):
        oline = line
        if len(line.strip()) > 0 and line.strip()[0] == '#':
            # Skip comments
            continue

        match = re.match(include_pattern, line)
        if match:
            filename = match.group('file')
            if filename not in included:
                included_source, included_file = read_file(filename,
                                                           search_path)
                included.append(included_file)
                line, included = preprocess(included_source, search_path,
                                            included)
            else:
                line = ""

        processed.append(line)

    return '\n'.join(processed), included

if __name__ == "__main__":
    parser = argparse.ArgumentParser("Compile λ-LISP programs")
    parser.add_argument('source', nargs='?', default='/dev/stdin', help="File to compile (default=stdin)")
    parser.add_argument('-v', '--verbose', action='count', default=0, help="Increase verbosity")
    parser.add_argument('-I', action='append', help="Add to include directory search path")
    args = parser.parse_args()

    if args.I:
        include_path = args.I
    else:
        include_path = []
    include_path.insert(0, os.path.dirname(args.source))

    # Search for original source file relative to current path
    source, _ = read_file(args.source, ['.'])

    # Search for included source files relative to source path
    preprocessed, _ = preprocess(source, include_path)

    program = Program(args.verbose)
    # Region for main program
    region = program.new_region()

    tokenized = tokenize(preprocessed)

    try:
        while tokenized:
            e = read_from(tokenized)
            expression = Expression(e, program, region)
            expression.emit()

        # Return at the end of the main program,
        if program.regions[region].getvalue():
            program.debug_comment(region, 2, "Return from main program")
            Rtn(program, region).emit()
    finally: # Always emit what we have, even in an exceptional case
        program.emit()
