#!/usr/bin/env python3

import fileinput
import re

instructions = [
    'LDC',
    'LD',
    'ADD',
    'SUB',
    'MUL',
    'DIV',
    'CEQ',
    'CGT',
    'CGTE',
    'ATOM',
    'CONS',
    'CAR',
    'CDR',
    'SEL',
    'JOIN',
    'LDF',
    'AP',
    'RTN',
    'DUM',
    'RAP',
    'STOP',
    'TSEL',
    'TAP',
    'TRAP',
    'ST',
    'DBUG',
    'BRK',
]
# | regexes are non-greedy, they will accept the first
# match, so they need to be sorted longest to shortest
# to behave "greedy"
instructions.sort(key=lambda n: len(n), reverse=True)

patterns = {
    'label': re.compile(r"""
            ^                   # Labels begin at column 0, no whitespace
            (?P<label>
                [A-Za-z_]+      # They begin with a letter or underscore
                [A-Za-z0-9_]*   # Contain letters, underscores, and numbers
            ):                  # They end in a comma
            """, re.VERBOSE),
    'instr': re.compile(r"""
            ^\s*                # Instructions are preceded only by whitespace
            (?P<instr>""" +
                "|".join(instructions) +    # They must be a valid instr name
            r""")
            (\s+                        # Optionally followed by an operand
                (?P<op1>[A-Za-z0-9_]+)  # Which is a number or label
            )?
            (\s+                        # Optionally followed by a second operand
                (?P<op2>[A-Za-z0-9_]+)  # Which is a number or label
            )?
            """, re.VERBOSE),
}

if __name__ == "__main__":
    addr = 0
    labels = {}

    # Pass 1: find all labels and their address
    for line in fileinput.input():
        label = re.match(patterns['label'], line)
        if label:
            labels[label.group('label')] = addr

        instr = re.match(patterns['instr'], line)
        if instr:
            addr += 1

    # Pass 2: replace all references
    for line in fileinput.input():
        match = re.match(patterns['instr'], line)
        if match:
            instr = match.group('instr')
            op1 = match.group('op1')
            op2 = match.group('op2')

            print(instr, end="")

            if op1:
                if op1 in labels:
                    val = labels[op1]
                else:
                    val = op1
                print("\t%s" % val, end="")
            if op2:
                if op2 in labels:
                    val = labels[op2]
                else:
                    val = op2
                print("\t%s" % val, end="")

            print("")
